### ISSUE TITLE
Please upload Solr schema and config

### ISSUE THREAD

**Issue by DmitryKey** [Salemmous/KoodiKirput#18]
The subj.

**Comment by Salemmous** [comment]
We just have the one created by Solr, since we decided to add our data to index with a GET request as shown here: https://lucene.apache.org/solr/guide/6_6/uploading-data-with-index-handlers.html#UploadingDatawithIndexHandlers-UsingcurltoPerformUpdates

**Comment by Panucho** [comment]
@DmitryKey #18 Does this need still more clarification?

**Comment by DmitryKey** [comment]
@Panucho it would be best if you uploaded schema and solrconfig to your project. This is because these two are evolving part of any Solr installation.

**Comment by Panucho** [comment]
@DmitryKey I just uploaded the files:
- https://github.com/Salemmous/KoodiKirput/blob/master/solrconfig.xml
- https://github.com/Salemmous/KoodiKirput/blob/master/managed-schema

**Comment by DmitryKey** [comment]
Very good, thanks @Panucho
