### ISSUE TITLE
Basic instructions

### ISSUE THREAD

**Issue by DmitryKey** [Salemmous/KoodiKirput#19]
Please update Readme.md with Basic instructions for how to run your code, what input it expects, what output to expect and if there are any edge cases (something not supported etc).

**Comment by Panucho** [comment]
@DmitryKey #19 Are the instructions clear enough?

**Comment by Panucho** [comment]
#19 The instructions follow now GitHub's syntax and formatting method.

**Comment by DmitryKey** [comment]
Looking better, thanks! You can close this issue.

**Comment by Panucho** [comment]
#19 Ok. Thanks!
